Support for breadcrumbs in container-ripe
ripe-tech/ripe-components-vue pull request #355
Opened 2020-08-28 11:34 UTC by NFSS10

| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | -- |
| Decisions | • Prop `title` in `container-ripe` and `details-ripe`component now accepts `array`'s so that we can choose between breadcrumbs and text <br>• Updated `container-ripe` and `details-ripe` storybook stories |
| Animated GIF | **`container-ripe`:**<br>![container-use_breadcrumbs_when_title_is_array](https://user-images.githubusercontent.com/22588915/91556400-91121100-e92a-11ea-9cfa-cade4a3522eb.gif)<br><br>**`details-ripe`:**<br><img width="1313" alt="imagem" src="https://user-images.githubusercontent.com/22588915/91556436-a129f080-e92a-11ea-838c-9714012634f4.png"> |

2020-08-28 11:43 UTC, gcandal requested changes
No need to modify the Storybook. If we dump all the new enhancements there they'll become unmanageable. Their point is to broadly show what can a component do, not to showcase every kind of functionality.

Aren't there more components that use `container-ripe` that need their `title` changed to `type: String | Array`?

2020-08-28 11:55 UTC, NFSS10 commented
> No need to modify the Storybook. If we dump all the new enhancements there they'll become unmanageable. Their point is to broadly show what can a component do, not to showcase every kind of functionality.
> 
> Aren't there more components that use `container-ripe` that need their `title` changed to `type: String | Array`?


Yes, `listing` and I kind hoped that you also asked about it. That one is a little weird as it doesn't use the prop `title`. It uses a prop `titleText`. It then builds the title text based on some rule that can or not use prefix. [See line 10](https://github.com/ripe-tech/ripe-components-vue/blob/5b4c85b594418d9f1c15be6b42e107380cf6d780/vue/components/ui/organisms/listing/listing.vue#L10
).

1- For this one we could have a prop breadcrums that if set would have priority over that rule
or
2- Probably the correct approach, change prop `titleText` -> `title`, accepts `String` and `Array` and then go to all other projects and update the component 😅

2020-08-28 11:58 UTC, gcandal commented
> > No need to modify the Storybook. If we dump all the new enhancements there they'll become unmanageable. Their point is to broadly show what can a component do, not to showcase every kind of functionality.
> > Aren't there more components that use `container-ripe` that need their `title` changed to `type: String | Array`?
> 
> Yes, `listing` and I kind hoped that you would asked about it. That one is a little weird as it doesn't use the prop `title`. It uses a prop `titleText`. It then builds the title text based on some rule that can or not use prefix. [See line 10](https://github.com/ripe-tech/ripe-components-vue/blob/5b4c85b594418d9f1c15be6b42e107380cf6d780/vue/components/ui/organisms/listing/listing.vue#L10).
> 
> 1- For this one we could have a prop `breadcrums` that if set would have priority over that rule
> or
> 2- Probably the correct approach, change prop `titleText` -> `title`, accepts `String` and `Array` and then go to all other projects and update the component 😅

Hm let's leave that one untouched, too much trouble for something we still don't have a use case for.

2020-08-28 13:56 UTC, gcandal commented on vue/components/ui/organisms/details/details.vue
> +                    </title-ripe>
Apply this strategy "v-if=array + v-else" to `vue/components/ui/atoms/container/container.vue`

2020-08-28 14:24 UTC, gcandal approved these changes

2020-08-31 10:51 UTC, joamag requested changes

2020-08-31 10:51 UTC, joamag commented on vue/components/ui/atoms/container/container.vue
> +                    v-if="title && Array.isArray(title)"
`hasBreadcrumbs` as computed

2020-09-01 09:30 UTC, gcandal approved these changes

2020-09-01 09:39 UTC, joamag approved these changes

2020-09-01 09:39 UTC, merged