Entity editor and creator components
ripe-tech/ripe-components-vue pull request #382
Opened 2020-09-29 16:24 UTC by NFSS10

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-registry/issues/1 |
| Dependencies | https://github.com/ripe-tech/ripe-components-vue/pull/378 |
| Decisions | Created `entity-creator` and `entity-editor`|
| Animated GIF | -- |

2020-10-01 11:32 UTC, gcandal requested changes
Make the changes required for https://github.com/ripe-tech/ripe-registry-ui/pull/16/files/04638052dc5740b8a5eec8995d21105460457f85#r498173503

2020-10-01 16:50 UTC, gcandal requested changes

2020-10-01 16:50 UTC, gcandal commented on vue/components/ui/organisms/form/form.vue
> +                    small: true,
Move these changes to https://github.com/ripe-tech/ripe-components-vue/pull/378

2020-10-02 10:16 UTC, gcandal approved these changes

2020-10-09 15:51 UTC, joamag commented
@gcandal reassigning to you

2021-02-24 09:43 UTC, gcandal commented
@joamag this seems like a pre-requisite for the new Twitch milestone.

2021-02-24 15:17 UTC, joamag commented
Yeah we must close this one once possible

2021-03-04 15:15 UTC, gcandal commented
The diff is messed up, re-opening the PR.

2021-03-04 15:15 UTC, closed without merging