#215 Input color
ripe-tech/ripe-components-vue pull request #393
Opened 2020-10-26 14:54 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-design/issues/215 |
| Decisions | Add input color component using native HTML input of type color. |
| Animated GIF | <img width="889" alt="image" src="https://user-images.githubusercontent.com/24736423/97187899-d459f600-179a-11eb-95c2-457b54c69a67.png"> |

2020-10-26 15:43 UTC, gcandal requested changes

2020-10-26 15:43 UTC, gcandal commented on vue/test/components/input-color/input-color.test.js
> +describe("InputColor", () => {
Please improve this by adding tests where you change the value in the input and checking that the color changes.

2020-10-26 15:43 UTC, gcandal commented on vue/components/ui/molecules/input-color/input-color.vue
> +    <div class="input-color-container" v-bind:class="classes">
Can we add some kind of visual feedback for when there's an error? (invalid color etc) Showing an empty color box, for instance.

2020-10-26 15:43 UTC, gcandal commented on vue/components/ui/molecules/input-color/input-color.vue
> +            v-show="false"
`display: none` instead please

2020-10-26 15:43 UTC, gcandal commented on vue/components/ui/molecules/input-color/input-color.vue
> +            this.$emit("update:value", value);
Move to the watcher, since it's the approach we are trying to use in "all" places

2020-10-26 15:43 UTC, gcandal commented on vue/components/ui/molecules/input-color/input-color.vue
> +    border-color: $red;
Let's avoid any kind of change altogether, just don't show any border

2020-10-26 18:08 UTC, gcandal requested changes
Let's work with `ffffff` instead of `#ffffff`. We need to find a strategy to include a `#` without needing the user to write. This is useful for several WYSYIG components. Think of a strategy and let's talk about it.

2020-10-26 18:14 UTC, 3rdvision commented
> Let's work with `ffffff` instead of `#ffffff`. We need to find a strategy to include a `#` without needing the user to write. This is useful for several WYSYIG components. Think of a strategy and let's talk about it.

How about
```
colorComputed() {
    return this.hasValidColor ? `#${this.valueData}` : "#ffffff";
},
...
        /**
         * Weather or not `valueData` is a string with valid hex color code.
         * @returns true if `valueData` is a string with a valid hex color code or false if otherwise.
         */
        hasValidColor() {
            return /^#([0-9A-F]{3}){1,2}$/i.test(`#${this.valueData}`);
        }
```

2020-11-04 16:33 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +        colorComputed() {
colorPrefixed

2020-11-04 16:34 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +        inputColorNativeValue() {
valueNative

2020-11-04 16:35 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +        height: {
delete

2020-11-04 16:35 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +        variant: {
inputProps

2020-11-04 16:35 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +            this.valueData = value.replaceAll("#", "");
Just at 0

2020-11-04 16:36 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +            this.valueData = value.replace("#", "");
setValue

2020-11-04 16:36 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +            this.valueData = value;
setValue

2020-11-04 16:37 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +            valueData: null
value

2020-11-04 16:37 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +        valueData(value) {
delete

2020-11-04 16:40 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +        this.valueData = this.value;
data

2020-11-04 16:42 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +            v-bind:value.sync="valueData"
v-bind:value="valueData.replace("#", "")
v-on:update:value="newValue => valueData = # + newValue"

2020-11-11 18:11 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +        valueNative() {
inputvalue

2020-11-11 18:11 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +            return /^#([0-9A-F]{3}){1,2}$/i.test(`#${this.valueData}`);
colorPrefixed

2020-11-11 18:11 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +            default: "#000000"
delete #

2020-11-11 18:12 UTC, 3rdvision commented on vue/components/ui/molecules/input-color/input-color.vue
> +            default: () => {}
```suggestion
            default: () => ({})

```

2020-11-11 18:27 UTC, gcandal approved these changes

2020-11-17 14:55 UTC, NFSS10 commented
> 
> 
> Let's work with `ffffff` instead of `#ffffff`. We need to find a strategy to include a `#` without needing the user to write. This is useful for several WYSYIG components. Think of a strategy and let's talk about it.

@gcandal, @3rdvision The value should always be without the "#" right? I think the component has an issue, see the GIF below:
![color_problem](https://user-images.githubusercontent.com/22588915/99405705-f3a0fa80-28e4-11eb-9058-52ed2ecab946.gif)

2020-11-17 15:37 UTC, 3rdvision commented
> > Let's work with `ffffff` instead of `#ffffff`. We need to find a strategy to include a `#` without needing the user to write. This is useful for several WYSYIG components. Think of a strategy and let's talk about it.
> 
> @gcandal, @3rdvision The value should always be without the "#" right? I think the component has an issue, see the GIF below:
> ![color_problem](https://user-images.githubusercontent.com/22588915/99405705-f3a0fa80-28e4-11eb-9058-52ed2ecab946.gif)

@NFSS10 It's a bit confusing now, in the initial implementation `input-color` accepted an hex color with or without "#" and would output `#HEX_VALUE` but that changed to: accept an hex color value without "#" and output an hex color value with "#". 

The current problem is colorPrefixed is not getting the init trigger to update the value sent sent by prop and the first value is always the same as the prop which is without the "#".

@gcandal I can refactor this so input and output are in the same format - an hex color value without "#".

2020-11-17 15:38 UTC, gcandal commented
> @gcandal I can refactor this so input and output are in the same format - an hex color value without "#".

Go for it!

2020-11-17 15:50 UTC, gcandal commented on vue/components/ui/molecules/input-color/input-color.vue
> +            this.valueData = value;
Let's try and make this uniform with other components:
- watcher on `valueData` just emits
- `onUserInput` calls `setValue`
- `setValue` just `this.valueData = value.replace("#", "");`

2020-11-17 18:25 UTC, gcandal approved these changes

2020-11-17 22:54 UTC, joamag approved these changes

2020-11-17 22:54 UTC, merged

2020-11-17 22:54 UTC, joamag commented
👏