#217 Button icon toggle
ripe-tech/ripe-components-vue pull request #394
Opened 2020-10-26 15:49 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-design/issues/217 |
| Decisions | Add button icon toogle based on button-icon component to add internal value toggle logic. |
| Animated GIF | <img width="731" alt="image" src="https://user-images.githubusercontent.com/24736423/97194778-74674d80-17a2-11eb-96d5-33de2992f138.png"> |

2020-10-26 18:14 UTC, gcandal commented on vue/test/components/button-icon-toggle/button-icon-toggle.test.js
> +const assert = require("assert");
Come on, you can do better :D

2020-10-26 18:15 UTC, gcandal commented on vue/test/components/button-icon-toggle/button-icon-toggle.test.js
> +const assert = require("assert");
(more tests)

2020-11-04 16:44 UTC, 3rdvision commented on vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
> +        v-bind:icon="iconComputed"
attrs

2020-11-04 16:46 UTC, 3rdvision commented on vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
> +            default: null
make up some default

2020-11-04 16:47 UTC, 3rdvision commented on vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
> +            default: null
define a default

2020-11-04 16:47 UTC, 3rdvision commented on vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
> +            animating: false,
delete

2020-11-05 11:33 UTC, gcandal requested changes

2020-11-05 11:33 UTC, gcandal commented on vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
> +         * If none is received, `icon` will be considered instead.
No longer true, right?

2020-11-05 11:33 UTC, gcandal commented on vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
> +         * @values true, false
No need for this, we know what a Boolean is :D

2020-11-05 11:33 UTC, gcandal commented on vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
> +        }
You can assume both secondary are required or have a default, so the fallback is not needed.

2020-11-06 16:32 UTC, gcandal commented
@3rdvision please substitute the PNG with a GIF. You might argue that going to the storybook is the same, but when you have 80 PRs to review this stuff matters.

2020-11-06 17:47 UTC, gcandal approved these changes

2020-11-07 12:58 UTC, joamag requested changes

2020-11-07 12:58 UTC, joamag commented on vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.stories.js
> +        <div>
fix indentation

2020-11-07 12:59 UTC, joamag approved these changes

2020-11-07 13:00 UTC, merged