feat: switcher text and color props
ripe-tech/ripe-components-vue pull request #457
Opened 2021-03-10 16:24 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-twitch/issues/42 |
| Dependencies | -- |
| Decisions | Switcher support for text on checked and unchecked status, and checked color. |
| Animated GIF |![switcher-text](https://user-images.githubusercontent.com/25725586/110661931-f2118000-81bc-11eb-802e-9a2f9697168c.gif)![switcher-use-case](https://user-images.githubusercontent.com/25725586/110661938-f342ad00-81bc-11eb-84d7-44f2c121f320.gif)|

2021-03-10 16:37 UTC, gcandal commented
Can't you use an approach similar to https://github.com/ripe-tech/ripe-twitch-ui/blob/master/components/atoms/button-twitch/button-twitch.vue ? Namely: using this component in a switcher-twitch and then v-deep everything?

2021-03-10 16:53 UTC, gcandal commented
The issue with using props to set the style is that will always be limited. If it was only one or two colors it would be ok but this commit includes CSS too, which is always risky.

However, with "v-deep inheritance", the sky is the limit, so in this particular instance let's go with it. In the future, it might make sense to add more props

2021-03-11 15:25 UTC, gcandal approved these changes

2021-03-11 15:38 UTC, joamag commented
Need two things:
* Where is this going to be used (different colors)
* Good rationale for the text as the switch component does not include text as of now

2021-03-11 15:42 UTC, BeeMargarida commented
> Need two things:
> 
>     * Where is this going to be used (different colors)
> 
>     * Good rationale for the text as the switch component does not include text as of now

Added to the PR description. Its necessary for the new designs of twitch-admin-ui where its necessary not only to switch the color, but also to show the meaning of both states of the switcher with the text on the right.

2021-03-11 15:44 UTC, joamag commented
> > Need two things:
> > ```
> > * Where is this going to be used (different colors)
> > 
> > * Good rationale for the text as the switch component does not include text as of now
> > ```
> 
> Added to the PR description. Its necessary for the new designs of twitch-admin-ui where its necessary not only to switch the color, but also to show the meaning of both states of the switcher with the text on the right.

We're not moving forward with those designs

2021-03-11 15:59 UTC, joamag requested changes

2021-03-11 15:59 UTC, joamag commented on vue/components/ui/atoms/switcher/switcher.vue
> +    position: relative;
remove the position relative

2021-03-11 16:12 UTC, joamag commented
Just talked with @gcandal we'll move with part of the changes defined extended the component scope

2021-03-11 16:22 UTC, gcandal commented
@joamag done.

2021-03-12 11:50 UTC, joamag approved these changes

2021-03-12 11:50 UTC, merged

2021-03-12 11:51 UTC, joamag commented
@gcandal we need to back-port this. Note that the grey version should be the default to one to ripe white