feat: add autorefresh to filter component
ripe-tech/ripe-components-vue pull request #520
Opened 2021-07-05 14:34 UTC by beneditomauro

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/220 |
| Decisions | add a parameter in the refresh function |

2021-07-05 15:26 UTC, NFSS10 requested changes
@beneditomauro also:
- don't forget to add `#<number_of_issue>` in the PR title.
- name your branches `t-mb/<issue_number>-<name>`

as it makes it easier to find thing related to the issue :)

2021-07-05 15:26 UTC, NFSS10 commented on vue/components/ui/organisms/listing/listing.vue
> +                                v-bind:loading="loading || autoRefreshing"
Make this a computed

2021-07-05 15:26 UTC, NFSS10 commented on vue/components/ui/molecules/filter/filter.vue
> +            this.loading = true && !auto;
`this.loading = !auto`

2021-07-05 15:26 UTC, NFSS10 commented on vue/components/ui/molecules/filter/filter.vue
> +                this.$emit("auto:refresh:start");
Why is this event needed?
It seems is because of some loading, but we already have the `update:loading` event for those things

2021-07-05 15:26 UTC, NFSS10 commented on vue/components/ui/molecules/filter/filter.vue
> +                const freshItems = newItems.reduce((a = 0, b) => a + !oldItems.includes(b), 0);
This is confusing, I would add a comment explaining what happens,

2021-07-05 15:26 UTC, NFSS10 commented on vue/components/ui/molecules/filter/filter.vue
> +
Add  `this.$emit("auto:refresh:stop");` here?

You have that before returning a few lines below

2021-07-05 15:26 UTC, NFSS10 commented on vue/components/ui/organisms/listing/listing.vue
> +            autoRefreshing: false,
Do we need this? Can't we use just `loading`

2021-07-05 15:41 UTC, NFSS10 commented
> 
> 
> > @beneditomauro also:
> > 
> > * don't forget to add `#<number_of_issue>` in the PR title.
> > * name your branches `t-mb/<issue_number>-<name>`
> > 
> > as it makes it easier to find thing related to the issue :)
> 
> Normally, when the issue is not from the repo the PR belongs to, I don't put it in the branch/PR name, only in the details

But is all associated with an issue. It makes it easier to track things.

2021-07-05 15:45 UTC, beneditomauro commented
> > > @beneditomauro also:
> > > 
> > > * don't forget to add `#<number_of_issue>` in the PR title.
> > > * name your branches `t-mb/<issue_number>-<name>`
> > > 
> > > as it makes it easier to find thing related to the issue :)
> > 
> > 
> > Normally, when the issue is not from the repo the PR belongs to, I don't put it in the branch/PR name, only in the details
> 
> But is all associated with an issue. It makes it easier to track things.

But putting the #220 in this, will automatically make you think this is related to  https://github.com/ripe-tech/ripe-components-vue/pull/220, when it's in fact 220 from other repo. I really think it's misleading, and you will never guess that the '220' is from pulse or whatever the case the other repo is, don't know if you agree with me on this or at least see the point I am making

2021-07-05 15:47 UTC, NFSS10 commented
> 
> 
> > > > @beneditomauro also:
> > > > 
> > > > * don't forget to add `#<number_of_issue>` in the PR title.
> > > > * name your branches `t-mb/<issue_number>-<name>`
> > > > 
> > > > as it makes it easier to find thing related to the issue :)
> > > 
> > > 
> > > Normally, when the issue is not from the repo the PR belongs to, I don't put it in the branch/PR name, only in the details
> > 
> > 
> > But is all associated with an issue. It makes it easier to track things.
> 
> But putting the #220 in this, will automatically make you think this is related to #220, when it's in fact 220 from other repo. I really think it's misleading, and you will never guess that the '220' is from pulse or whatever the case the other repo is, don't know if you agree with me on this or at least see the point I am making

Yes, I see what you are saying

2021-07-06 09:48 UTC, NFSS10 requested changes
Also, please mark the comments as resolved when you handle them in the review, so I can have a better picture of what is in discussion or what you handled in the review iteration

2021-07-06 09:48 UTC, NFSS10 commented on vue/components/ui/molecules/filter/filter.vue
> +                const freshItems = newItems.reduce((a = 0, b) => a + !oldItems.includes(b), 0);
I think we just use inline comments, no need for `@param`, just add a small text explaining whats going on

2021-07-06 09:48 UTC, NFSS10 commented on vue/components/ui/molecules/filter/filter.vue
> +                this.autoRefreshing = true;
I think there is a case where this isn't set to `false`.

if `auto` and `freshItems` it returtns without setting autoRefreshing to `false` please double check if the logic is right

2021-07-06 09:48 UTC, NFSS10 commented on vue/components/ui/organisms/listing/listing.vue
> +            this.autoRefreshing = false;
Dead code?

2021-07-06 09:48 UTC, NFSS10 commented on vue/components/ui/organisms/listing/listing.vue
> +                v-on:update:loading="onUpdateLoading"
No need, its already binding to loading

2021-07-06 09:48 UTC, NFSS10 commented on vue/components/ui/molecules/filter/filter.vue
> +            autoRefreshing: false,
Is this really needed? Couldn't you just change `loading` state?

2021-07-12 11:02 UTC, gcandal commented on vue/components/ui/molecules/filter/filter.vue
> +            autoRefreshing: false,
`filter` can't have any reference to autorefreshing, everything must be in the mixin

2021-07-12 11:02 UTC, gcandal commented on vue/components/ui/molecules/filter/filter.vue
> +        async refresh({ force = true, auto = false } = {}) {
> filter can't have any reference to autorefreshing, everything must be in the mixin

So you'll to change the parameter name to something like `loading`

2021-07-12 15:32 UTC, gcandal commented on CHANGELOG.md
>  *
Delete the empty `*`

2021-07-12 15:32 UTC, gcandal commented on vue/mixins/refresh.js
> +        autoRefreshTime: {
```suggestion
        autoRefreshInterval: {
```

2021-07-12 15:49 UTC, gcandal approved these changes

2021-07-26 13:41 UTC, beneditomauro commented
@gcandal re-requestiing review on this as support for a switcher to control autorefresh was added originated by: https://github.com/ripe-tech/ripe-util-vue/issues/137

2021-07-26 13:53 UTC, joamag commented
@gcandal please help here with the original idea of having a mixing that provides global page refresh from time to time
Ideally it should be possible to configure the timeout interval time and if it's enabled or disabled

2021-07-30 10:38 UTC, gcandal commented
Closing and re-using some of the components of this to move to a "whole page" refresh approach.

2021-07-30 10:38 UTC, closed without merging

2021-07-30 10:51 UTC, gcandal commented
https://github.com/ripe-tech/ripe-components-vue/pull/526