Added Expandable Section
ripe-tech/ripe-components-vue pull request #554
Opened 2022-02-28 17:25 UTC by veryprofessionaldodo

| - | - |
| --- | --- |
| Issue | Requested in the issue https://github.com/ripe-tech/ripe-util-vue/issues/247 |
| Decisions | There was a need to a section that could be collapsed or expanded at will. This PR adds a new `section-expandable-ripe` component, that is similar to the basic `section` component, with the extra logic for the collapse of information. |
| Screenshots | ![Screen Recording 2022-02-28 at 17 17 16](https://user-images.githubusercontent.com/22790704/156029306-03f57ffb-54ef-4c4f-96d8-3b31d5db399a.gif) Don't know why it's in slow-motion, but it's in regular speed when using! |

2022-02-28 18:53 UTC, joaofsl requested changes

2022-02-28 18:53 UTC, joaofsl commented on vue/components/ui/molecules/section-expandable/section-expandable.vue
> +        }
remove unused prop

2022-02-28 18:53 UTC, joaofsl commented on vue/components/ui/molecules/section-expandable/section-expandable.vue
> +    mounted: function() {
mounted before methods

2022-02-28 19:48 UTC, joaofsl commented on vue/components/ui/molecules/section-expandable/section-expandable.vue
> +    mounted: function() {
also, extract it to a function so it can be called from the outside in case we need to recompute the height

2022-03-01 09:50 UTC, joaofsl approved these changes
👌🏼

2022-03-01 12:16 UTC, hugo-gomes approved these changes

2022-03-01 12:32 UTC, hugo-gomes reviewed
@veryprofessionaldodo was this design by UI/UX?

2022-03-01 12:33 UTC, joamag approved these changes

2022-03-01 12:33 UTC, merged

2022-03-01 13:39 UTC, veryprofessionaldodo commented
@hugo-gomes The design was copied from the `table-expandable` component, but this design itself was not done by UI/UX. The guidelines were pretty straightforward [on the issue](https://github.com/ripe-tech/ripe-util-vue/issues/247), so I just followed that :)