Remove Stroke for Spreadsheet Icon
ripe-tech/ripe-components-vue pull request #560
Opened 2022-03-15 11:36 UTC by veryprofessionaldodo

| - | - |
| --- | --- |
| Decisions | Icon had stroke properties incorrectly, and had to be manually removed in CSS. |

2022-03-15 12:55 UTC, joaofsl approved these changes

2022-03-15 12:58 UTC, NFSS10 requested changes
Missing changelog, also add #<issue number> in this PR title

Also, won't this change affect other projects?

2022-03-15 14:29 UTC, veryprofessionaldodo commented
@NFSS10 Is this really changelog worthy? It's a small update on an icon that was added a day ago, and there's only one project that uses this icon, that being ripe-pulse, and there was a [request to remove custom CSS for this](https://github.com/ripe-tech/ripe-pulse/pull/313#discussion_r826847517).

2022-03-19 16:47 UTC, joamag approved these changes

2022-03-19 16:47 UTC, merged