feat: disabled button icon dropdown
ripe-tech/ripe-components-vue pull request #570
Opened 2022-03-31 16:24 UTC by joao-conde

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/281 |
| Dependencies | -- |
| Decisions | Disable the button icon dropdown prop. |
| Animated GIF | ![button icon dropdown disable](https://user-images.githubusercontent.com/16060539/161103897-ab70e5f5-6846-4847-a99d-226ebcb5da60.gif) |

2022-03-31 16:30 UTC, BeeMargarida requested changes

2022-03-31 16:30 UTC, BeeMargarida commented on vue/components/ui/molecules/button-icon-dropdown/button-icon-dropdown.stories.js
> +            disabled: false
this could be controllable in the story, like `disabled: boolean("Disabled", false)`

2022-04-01 17:09 UTC, BeeMargarida approved these changes

2022-04-01 17:29 UTC, 3rdvision approved these changes

2022-04-01 18:24 UTC, joamag approved these changes

2022-04-01 18:24 UTC, merged