#316 Support custom panel in `header-ripe`
ripe-tech/ripe-components-vue pull request #573
Opened 2022-04-06 08:02 UTC by NFSS10

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/316 |
| Dependencies | -- |
| Decisions | • Add proper `dropdown` click event that supports `event` parameter (maitaining backwards compatibility)<br>• Support customization of the account dropdown list in the `header-ripe` component<br>• Support custom panel in the `header-ripe` component |

https://user-images.githubusercontent.com/22588915/161925503-89e5c0ef-e201-4fd2-abd3-e3a482741cb1.mov

https://user-images.githubusercontent.com/22588915/161925494-f08e3e51-4966-45d1-ba90-d23f1a4edd63.mov

2022-04-06 15:00 UTC, veryprofessionaldodo requested changes

2022-04-06 15:20 UTC, NFSS10 commented on vue/components/ui/organisms/header/header.vue
> +                        v-bind:items="_accountDropdownItems"
What do you propose?

2022-04-06 16:21 UTC, veryprofessionaldodo commented on vue/components/ui/organisms/header/header.vue
> +                        v-bind:items="_accountDropdownItems"
Good question. Perhaps `accountDropdownItemsExtra`?

2022-04-08 17:18 UTC, veryprofessionaldodo approved these changes

2022-04-11 08:49 UTC, beneditomauro approved these changes

2022-04-11 11:55 UTC, joamag approved these changes

2022-04-11 11:55 UTC, merged

2022-04-11 19:29 UTC, joamag commented
@NFSS10 let's backport the dropdown changes to the ripe-white solution or any other projects if it makes sense