Ripe copper update have shipping information
ripe-tech/ripe-components-vue pull request #575
Opened 2022-04-06 15:56 UTC by beneditomauro

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-copper/issues/48 |
| Animated GIF | ![5k9jAs7JOw](https://user-images.githubusercontent.com/8842023/162016574-cfcc65cf-f95b-454c-9d3a-de3996eb99eb.gif) |

2022-04-06 15:56 UTC, beneditomauro commented
NOTE: https://github.com/ripe-tech/ripe-copper/issues/48#issuecomment-1090406250

2022-04-08 15:59 UTC, joaofsl requested changes
Canceling an update to the file shouldn't clear the previously uploaded file.
![](http://g.recordit.co/voQcG2zlvi.gif)

The close button doesn't have any feedback/indication that is actually clickable. Maybe add css for the hover?
![](http://g.recordit.co/iTuqpNSEeC.gif)

2022-04-08 15:59 UTC, joaofsl commented on vue/components/ui/molecules/input-file/input-file.vue
> +    padding-right: 12px;
do this in one line

2022-04-08 15:59 UTC, joaofsl commented on vue/components/ui/molecules/input-file/input-file.vue
> +            height: null,
this height is not being used

2022-04-08 15:59 UTC, joaofsl commented on vue/components/ui/molecules/input-file/input-file.vue
> +            greaterValue: null
this is also not being used

2022-04-08 15:59 UTC, joaofsl commented on vue/components/ui/molecules/input-file/input-file.vue
> +            return this.filesData.length === 0 ? this.text : this.filesData[0].name;
`this.filesData.length === 0` this condition is used multiple times, we should have a computed for it

2022-04-13 09:16 UTC, joaofsl requested changes

2022-04-13 09:16 UTC, joaofsl commented on vue/components/ui/molecules/input-file/input-file.vue
> +    mounted: function() {
mounted before methods

2022-04-13 09:16 UTC, joaofsl commented on vue/components/ui/molecules/input-file/input-file.vue
> +            if (!value || value.length === 0) this.clear();
Do we need this? Is this the logic to clear the files when you cancel the upload?

2022-04-13 09:53 UTC, joaofsl approved these changes

2022-04-13 09:57 UTC, joaofsl commented
@beneditomauro Maybe also update the GIF to display the hover on the remove button

2022-04-13 12:11 UTC, veryprofessionaldodo requested changes

2022-04-13 12:11 UTC, veryprofessionaldodo commented on vue/components/ui/molecules/input-file/input-file.vue
> +    background-color: #e6e6e6;
A small transition for the hover would look quite cool!

2022-04-13 12:11 UTC, veryprofessionaldodo commented on vue/components/ui/molecules/input-file/input-file.vue
> +                remove: !this.noFileSelected
I think that when no file was selected, the color for the text could be slightly less pronounced, since it's almost a placeholder.

2022-04-22 14:32 UTC, veryprofessionaldodo approved these changes

2022-04-22 14:33 UTC, veryprofessionaldodo commented
@beneditomauro Fix the conflicts, and then feel free to assign João directly!

2022-04-27 18:54 UTC, joamag approved these changes

2022-04-27 18:54 UTC, merged