Add `input-icon` component
ripe-tech/ripe-components-vue pull request #588
Opened 2022-05-04 08:44 UTC by veryprofessionaldodo

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/259 |
| Decisions | There was the need to have an `input` component capable of having icons before and after, so in order to preserve backwards compatibility with existing `input` usages, a new component was created, named `input-icon`. |
| Screenshots | <img width="345" alt="image" src="https://user-images.githubusercontent.com/22790704/166648804-77dc0b50-a01c-442c-a027-4a46c60bbc31.png"> |

2022-05-05 10:27 UTC, beneditomauro requested changes
Well, if this is a input that can have icons left or right, this should be a molecule with `<input />` and `<icon />` and not an input that can have whatever on the left and on the right.

Basically, if this is supposed to be a input with icon, use `icon` directly in the component

2022-05-05 13:53 UTC, veryprofessionaldodo commented
@beneditomauro I see what you mean. What would you suggest, that perhaps the naming of the file be changed? I think the flexibility is good, since I'm already using this on another PR with a loader, for example.

2022-05-12 08:41 UTC, beneditomauro requested changes
LGTM. Just add a quick example with slots in storybook

2022-05-12 11:00 UTC, beneditomauro approved these changes

2022-05-12 11:33 UTC, joaofsl approved these changes

2022-05-12 11:33 UTC, joaofsl commented on vue/components/ui/molecules/input-symbol/input-symbol.stories.js
> +                <h3>Using Slots</h3>
I know this is very picky, but let's avoid using h3

2022-05-13 21:07 UTC, joamag approved these changes

2022-05-13 21:07 UTC, merged