Add debounce delay to `input-symbol` component
ripe-tech/ripe-components-vue pull request #591
Opened 2022-05-19 09:31 UTC by veryprofessionaldodo

| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-util-vue/issues/259 |
| Decisions | It would be good to add the debounce delay to the `input-symbol` component, since it uses `input-ripe`. |

2022-05-20 14:18 UTC, NFSS10 requested changes

2022-05-20 14:18 UTC, NFSS10 commented on vue/components/ui/molecules/input-symbol/input-symbol.vue
> +            default: 0
Use `default: null` like here: https://github.com/ripe-tech/ripe-components-vue/blob/f0f04f154726ea4045ee8455520bef22925385a1/vue/components/ui/atoms/input/input.vue#L156

2022-05-20 16:33 UTC, NFSS10 approved these changes

2022-06-06 18:00 UTC, joaofsl approved these changes

2022-06-07 08:52 UTC, joamag approved these changes

2022-06-07 08:52 UTC, merged