`header ripe` improvements - Remove hardcoded announcements
ripe-tech/ripe-components-vue pull request #592
Opened 2022-05-19 10:16 UTC by NFSS10

| - | - |
| --- | --- |
| Issue | This change request originated when discussing https://github.com/ripe-tech/ripe-components-vue/pull/573 implementation |
| Dependencies | -- |
| Decisions | • Removed `announcements` component and it's related logic from `header-ripe` <br>• Generalize `header-ripe` notifications logic |

To maintain the announcements, just use the slot like it's done for the other panels. Example:
```javascript
<header-ripe v-bind=...>
        <template v-slot:extra-panel-announcements hide }">
            <announcements
                v-bind=...
                v-on:click:close="hide"
            />
        </template>
    </header-ripe>
```

The notifications aren't hardcoded anymore so to show them just set the dropdown item you want with a field `notification` to `true`. Example:
```javascript
[{ value: "announcements", label: "What's new?", notification: true }]
```

**Demo with `announcements` with notifications:**

https://user-images.githubusercontent.com/22588915/169267957-20ea56ee-da76-47bb-95fe-a915bfe5d850.mov

**Demo with `announcements` without notifications:**

https://user-images.githubusercontent.com/22588915/169267967-6bb3f504-f802-4e53-a669-63d708676cc5.mov

2022-05-23 13:09 UTC, beneditomauro requested changes
Check why CI is failing

2022-05-23 13:53 UTC, beneditomauro commented on CHANGELOG.md
> +* Removed `announcements` component and it's related logic from `header-ripe` component
okay, just found weird the error was not on `node 16` job

2022-05-23 13:53 UTC, beneditomauro approved these changes

2022-05-23 16:20 UTC, joaofsl approved these changes

2022-05-26 11:38 UTC, joamag approved these changes

2022-05-26 11:38 UTC, merged