#288 Export orders  - Fix button-dropdown
ripe-tech/ripe-components-vue pull request #593
Opened 2022-05-19 15:21 UTC by joaofsl

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/288 |
| Decisions |* Fix `button-dropdown` events not being propagated correctly<br>* Better button title so that the storybook doesn't cover half of the dropdown buttons|
| Animated GIF | <img  src="https://user-images.githubusercontent.com/10127604/169332996-19101d48-d114-4f89-bf0f-f332d3b6eca3.png">|

2022-05-20 14:55 UTC, NFSS10 requested changes
@joaofsl You should probably add the label "risky" as these are one of those changes that could in theory break stuff.

I know you checked that it wouldn't affect any of our projects, but I would still add the label :)

2022-05-20 14:55 UTC, NFSS10 commented on vue/components/ui/molecules/button-dropdown/button-dropdown.stories.js
> +                        Edit: "Edit dropdown",
You shouldn't change this, this `"Edit dropdown"` isn't an icon

2022-05-23 09:33 UTC, NFSS10 approved these changes

2022-05-23 15:07 UTC, veryprofessionaldodo approved these changes

2022-05-27 15:14 UTC, joamag approved these changes

2022-05-27 15:14 UTC, joamag commented
@joaofsl this may require back-porting of elements to ripe-commons-pluginus, etc.

2022-05-27 15:15 UTC, merged