#288 sortedItems Event
ripe-tech/ripe-components-vue pull request #600
Opened 2022-06-03 11:31 UTC by joaofsl

| - | - |
| --- | --- |
| Issue | Issue came up while reviewing https://github.com/ripe-tech/ripe-util-vue/issues/288 to access the sorted items |
| Decisions |Emit an event whenever the `sortedItems` are updated  |

2022-06-03 11:39 UTC, NFSS10 requested changes

2022-06-03 11:39 UTC, NFSS10 commented on vue/components/ui/molecules/table/table.vue
> +            this.$emit("update:sorted-items", sortedItems);
Don't do these kind of operations in a computed variable.

Add a watcher for the `sortedItems` computed variable and then do the emit operation there

2022-06-03 11:55 UTC, NFSS10 approved these changes

2022-06-03 15:55 UTC, beneditomauro requested changes

2022-06-03 15:55 UTC, beneditomauro commented on CHANGELOG.md
> +* Add event to emit `sortedItemd` on `table-ripe` - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
```suggestion
* Add event to emit `sortedItems` on `table-ripe` - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
``` 

or even maybe 

```suggestion
* Add `update:sorted-items` event in `table-ripe` - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
```

2022-06-05 14:13 UTC, beneditomauro approved these changes

2022-06-05 17:06 UTC, joamag approved these changes

2022-06-05 17:06 UTC, merged