#302 button-color loading improvements
ripe-tech/ripe-components-vue pull request #604
Opened 2022-07-04 11:07 UTC by joaofsl

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/pull/302 |
| Decisions |Add better loading style for other colors <br> Remove hover and interaction while loading <br>|
| Animated GIF |![](http://g.recordit.co/90MG7lowTP.gif)|

2022-07-04 11:23 UTC, NFSS10 requested changes

2022-07-04 11:23 UTC, NFSS10 commented on vue/components/ui/atoms/button-color/button-color.vue
> -        },
This prop shouldn't probably exist in the first place, but as it's there, I don't think we should remove it now to ensure we are maintaining retrocompatibility.

Just do this in the newly created computed variable `loaderStyle` (you will need to change it's name too):
```
        _loaderStyle() {
            const base = {};
            base["background-color"] = this.color === "white" ? "#2d2d2d" : "#e4e8f0";
            base = { ...base, ...this.loaderstyle };
            return base;
        }
```

2022-07-27 14:46 UTC, NFSS10 approved these changes

2022-07-27 22:37 UTC, beneditomauro requested changes

2022-07-27 22:37 UTC, beneditomauro commented on CHANGELOG.md
> +* Remove hover and interaction while loading - [288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
```suggestion
* Add better loading style for other colors - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
* Remove hover and interaction while loading - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
```

2022-08-17 10:27 UTC, beneditomauro approved these changes

2022-09-12 16:20 UTC, joamag approved these changes

2022-09-12 16:20 UTC, merged