#288 - Add new props to section-expandable
ripe-tech/ripe-components-vue pull request #608
Opened 2022-09-13 11:11 UTC by joaofsl

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/288 |
| Decisions | Made some improvements to the `section-expandable` component|

https://user-images.githubusercontent.com/10127604/189886586-bdc5a379-b385-4612-bf49-3743b14ebf74.mp4

2022-09-13 11:44 UTC, NFSS10 requested changes

2022-09-13 11:44 UTC, NFSS10 commented on vue/components/ui/molecules/section-expandable/section-expandable.vue
> +        style() {
I would rename `style` -> `titleStyle`

Also, as you are not set style with dynamic variables, you should use classes instead, as in, add a `uppercase` class and then have the changes be done via that class activation (like you do above for the title size)

2022-09-13 14:31 UTC, NFSS10 requested changes
@joaofsl Also don't forget to fix conflicts

2022-09-13 14:31 UTC, NFSS10 commented on vue/components/ui/molecules/section-expandable/section-expandable.vue
> +            default: true
The default should be `"medium"` String

2022-09-13 14:34 UTC, NFSS10 approved these changes

2022-09-14 14:22 UTC, beneditomauro approved these changes

2022-09-14 15:26 UTC, joao-conde approved these changes

2022-09-30 15:38 UTC, joamag approved these changes

2022-09-30 15:38 UTC, merged