#612 `upload-area` component not clearing data
ripe-tech/ripe-components-vue pull request #613
Opened 2022-10-26 15:01 UTC by beneditomauro

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/issues/612 |
| Decisions | -Move common logic to the `upload` mixin |
| Animated GIF | ![T0yp5QhkP8](https://user-images.githubusercontent.com/8842023/198069412-7231c2ab-3076-4992-8d4a-6bcfc3b5d04b.gif) |

2022-10-26 15:16 UTC, 3rdvision approved these changes

2022-10-26 15:44 UTC, joao-conde requested changes

2022-10-26 15:44 UTC, joao-conde commented on CHANGELOG.md
> +* `upload-area` component not clearing data - [#612](https://github.com/ripe-tech/ripe-util-vue/issues/612)
ripe-util-vue/#612

2022-10-26 15:50 UTC, beneditomauro commented on CHANGELOG.md
> +* `upload-area` component not clearing data - [#612](https://github.com/ripe-tech/ripe-util-vue/issues/612)
> ripe-util-vue/#612

This is a component related bug,

2022-10-26 16:01 UTC, joao-conde commented on CHANGELOG.md
> +* `upload-area` component not clearing data - [#612](https://github.com/ripe-tech/ripe-util-vue/issues/612)
Link is wrong then

2022-10-27 11:32 UTC, joamag approved these changes

2022-10-27 11:32 UTC, merged

2022-10-27 11:33 UTC, joamag commented
@beneditomauro good fix 👍