feat: add reacticity to `emptySlots()` computed propertie in `molecules/upload-area.vue`
ripe-tech/ripe-components-vue pull request #614
Opened 2022-10-27 15:15 UTC by beneditomauro

| - | - |
| --- | --- |
| Issue | - |
| Dependencies | - |
| Decisions |Conceptually, `computed` values in `vue` are used when logic needs to be triggered when component internal `state` changes weather the logic is conditional to the state itself. In this specific case, `emptySlots()` is running only one time on component creation, limiting use-cases when the parent component adds or removes slots accordingly (see screenshots below) not removing the button when a slot is added. What was done to fix this:  <br> <br> - Reference the respective data property to react to, and use it in a way that doesn't alter the returning boolean expression  |
| Animated GIF | No slots: <img width="718" alt="Screenshot 2022-10-27 at 15 56 46" src="https://user-images.githubusercontent.com/8842023/198324835-a6138751-4be8-4c81-84e6-239b23170498.png"> With slots:<img width="702" alt="Screenshot 2022-10-27 at 15 57 12" src="https://user-images.githubusercontent.com/8842023/198325121-2c8fcc19-a707-440c-af22-0f4defbd7192.png"> |

2022-10-27 15:24 UTC, 3rdvision commented
@beneditomauro are we able to reproduce this bug in components-vue storybook?

2022-10-27 15:26 UTC, beneditomauro commented
> @beneditomauro are we able to reproduce this bug in components-vue storybook?

Not as it is, we would have to add a story that inserts a slot after the component mounting

2022-10-28 14:39 UTC, 3rdvision requested changes

2022-10-28 14:39 UTC, 3rdvision commented on vue/components/ui/molecules/upload-area/upload-area.vue
> +            );
```suggestion
            return !this.noFileSelected && Object.entries(this.$slots).length === 0 && !this.$scopedSlots?.default;
```

use this instead and add this value to mixins/upload.js
```

    computed: {
        noFileSelected() {
            return this.filesData?.length === 0;
        }
    },
```

also, remove it from `input-file` component.

I think it looks more elegant. What do you say?

2022-10-28 16:22 UTC, 3rdvision commented on vue/mixins/upload.js
> +        noFileSelected() {
nice!
Also, don't forget to remove this one from `input-file` component since it is already importing this mixin :smile:

2022-11-02 09:29 UTC, 3rdvision commented
@beneditomauro tests are failing... can you check it out?

2022-11-02 15:19 UTC, beneditomauro commented
> @beneditomauro tests are failing... can you check it out?

This is not related to the PR, this is locally in master fails too:

<img width="1638" alt="Screenshot 2022-11-02 at 15 12 29" src="https://user-images.githubusercontent.com/8842023/199527331-7298af32-0e48-4535-8626-8014d65486ab.png">

2022-11-02 16:56 UTC, 3rdvision approved these changes
Approved and we need to solve the failing build in a separate PR

2022-11-02 17:24 UTC, joamag approved these changes

2022-11-02 17:26 UTC, merged