fix: view on white button
ripe-tech/ripe-components-vue pull request #621
Opened 2022-12-05 17:12 UTC by beneditomauro

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/357 |
| Dependencies | - |
| Decisions |- This regression was caused when we [added](https://github.com/ripe-tech/ripe-components-vue/pull/584/files) `iconPosition` prop |
| Animated GIF | <img width="1333" alt="Screenshot 2022-12-05 at 17 03 02" src="https://user-images.githubusercontent.com/8842023/205699488-547c4c1b-4d8f-4ec4-a873-1dcfe0a5ae4f.png">|

2022-12-09 10:53 UTC, joaofsl requested changes

2022-12-09 10:53 UTC, joaofsl commented on CHANGELOG.md
> +* Regression on view on white button - [ripe-pulse/#612](https://github.com/ripe-tech/ripe-pulse/issues/357)
Check this

2022-12-12 11:33 UTC, joaofsl approved these changes

2022-12-12 11:37 UTC, joao-conde approved these changes

2022-12-12 11:37 UTC, merged